services:
  api:
    build: ./
    volumes:
      - ./api:/var/www
    working_dir: /var/www
    command: php index.php
    ports:
      - "${API_PORT:-8080}:8080"
  front:
    image: nginx:latest
    volumes:
      - ./front:/usr/share/nginx/html
    ports:
      - "${HTTP_PORT:-80}:80"
